import { boolean, integer, jsonb, pgTable, serial, text, timestamp, uniqueIndex } from 'drizzle-orm/pg-core'

export const profiles = pgTable('profiles', {
  id: serial('id').primaryKey(),
  nickname: text('nickname').notNull(),
  avatar: text('avatar').notNull().default(''),
  titleZh: text('title_zh').notNull().default(''),
  titleEn: text('title_en').notNull().default(''),
  bioZh: text('bio_zh').notNull().default(''),
  bioEn: text('bio_en').notNull().default(''),
  yearsOfExperience: integer('years_of_experience').notNull().default(0),
  successRate: integer('success_rate').notNull().default(0),
  efficiencyGain: integer('efficiency_gain').notNull().default(0),
  email: text('email').notNull().default(''),
  phone: text('phone').notNull().default(''),
  wechatId: text('wechat_id').notNull().default(''),
  wechatQrcode: text('wechat_qrcode').notNull().default(''),
  linkedin: text('linkedin').notNull().default(''),
  github: text('github').notNull().default(''),
  zhihu: text('zhihu').notNull().default(''),
  emailDisplayed: boolean('email_displayed').notNull().default(true),
  phoneDisplayed: boolean('phone_displayed').notNull().default(false),
  wechatDisplayed: boolean('wechat_displayed').notNull().default(false),
  experiences: jsonb('experiences').$type<Array<Record<string, string>>>().notNull().default([]),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
})

export const skills = pgTable('skills', {
  id: serial('id').primaryKey(),
  nameZh: text('name_zh').notNull(),
  nameEn: text('name_en').notNull(),
  level: integer('level').notNull().default(0),
  category: text('category').notNull(),
  sortOrder: integer('sort_order').notNull().default(0),
  enabled: boolean('enabled').notNull().default(true),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
})

export const projects = pgTable('projects', {
  id: serial('id').primaryKey(),
  slug: text('slug').notNull(),
  nameZh: text('name_zh').notNull(),
  nameEn: text('name_en').notNull(),
  thumbnail: text('thumbnail').notNull().default(''),
  typeZh: text('type_zh').notNull().default(''),
  typeEn: text('type_en').notNull().default(''),
  introZh: text('intro_zh').notNull().default(''),
  introEn: text('intro_en').notNull().default(''),
  keywords: jsonb('keywords').$type<string[]>().notNull().default([]),
  tags: jsonb('tags').$type<string[]>().notNull().default([]),
  emoji: text('emoji').notNull().default(''),
  problemZh: text('problem_zh').notNull().default(''),
  problemEn: text('problem_en').notNull().default(''),
  actionZh: text('action_zh').notNull().default(''),
  actionEn: text('action_en').notNull().default(''),
  resultZh: text('result_zh').notNull().default(''),
  resultEn: text('result_en').notNull().default(''),
  contentZh: text('content_zh').notNull().default(''),
  contentEn: text('content_en').notNull().default(''),
  externalUrl: text('external_url').notNull().default(''),
  published: boolean('published').notNull().default(true),
  sortOrder: integer('sort_order').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
}, (table) => ({
  slugIndex: uniqueIndex('projects_slug_unique').on(table.slug),
}))

export const articles = pgTable('articles', {
  id: serial('id').primaryKey(),
  slug: text('slug').notNull(),
  titleZh: text('title_zh').notNull(),
  titleEn: text('title_en').notNull(),
  introZh: text('intro_zh').notNull().default(''),
  introEn: text('intro_en').notNull().default(''),
  keywords: jsonb('keywords').$type<string[]>().notNull().default([]),
  contentZh: text('content_zh').notNull().default(''),
  contentEn: text('content_en').notNull().default(''),
  published: boolean('published').notNull().default(true),
  publishedAt: timestamp('published_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
}, (table) => ({
  slugIndex: uniqueIndex('articles_slug_unique').on(table.slug),
}))

export const industryUpdates = pgTable('industry_updates', {
  id: serial('id').primaryKey(),
  slug: text('slug').notNull(),
  titleZh: text('title_zh').notNull(),
  titleEn: text('title_en').notNull(),
  introZh: text('intro_zh').notNull().default(''),
  introEn: text('intro_en').notNull().default(''),
  keywords: jsonb('keywords').$type<string[]>().notNull().default([]),
  contentZh: text('content_zh').notNull().default(''),
  contentEn: text('content_en').notNull().default(''),
  coverImage: text('cover_image').notNull().default(''),
  sources: jsonb('sources').$type<Array<{ name: string; url: string }>>().notNull().default([]),
  newsItems: jsonb('news_items').$type<Array<Record<string, unknown>>>().notNull().default([]),
  techItems: jsonb('tech_items').$type<Array<Record<string, unknown>>>().notNull().default([]),
  published: boolean('published').notNull().default(true),
  publishedAt: timestamp('published_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
}, (table) => ({
  slugIndex: uniqueIndex('industry_updates_slug_unique').on(table.slug),
}))

export const agentConfigs = pgTable('agent_configs', {
  id: serial('id').primaryKey(),
  mode: text('mode').notNull().default('auto'),
  provider: text('provider').notNull().default('openai'),
  model: text('model').notNull().default('gpt-4o-mini'),
  baseUrl: text('base_url').notNull().default('https://api.openai.com/v1'),
  maxToolRounds: integer('max_tool_rounds').notNull().default(3),
  systemPrompt: text('system_prompt').notNull().default(''),
  welcomeMessage: jsonb('welcome_message').$type<{ zh: string; en: string }>().notNull(),
  quickQuestions: jsonb('quick_questions').$type<Array<{ zh: string; en: string }>>().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
})
